### ISSUE TITLE
Boundary cases in test plan

### ISSUE THREAD

**Issue by AshwinG21** [dilipkumar26/SDLC_12_Iconics#1]
In the boundary scenarios in low level unit test plan, its like we can consider any value very close to the specific boundary preset. So it is a bit confusing.  I have just considered one boundary condition and i have uploaded that picuture over here. 

![Issue](https://user-images.githubusercontent.com/67604549/130271328-52aafe0d-636e-488a-a5a7-8c394b6c12f7.jpg)

**Comment by Sangamjain** [comment]
Got it,this one example value of 2200 ohms gives out the basic perspective of boundary test and moreover we have given boundary set values in low level test plan for different operations.
